{
 "title": "AMD GPU Metrics",
 "tags": [
  "gpu",
  "amd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "amd_gpu_usage_percent{type=\"gfx\"}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amd_gpu_temperature_celsius{type=\"edge\"}"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "amd_gpu_power_watts{type=\"socket\"}"
    }
   ]
  },
  {
   "title": "GPU Clock Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "amd_gpu_clock_mhz{type=\"gfx\"}"
    }
   ]
  },
  {
   "title": "VRAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "amd_gpu_memory_bytes{gpu=\"0\",type=\"used_vram\"} / ignoring(type) amd_gpu_memory_bytes{gpu=\"0\",type=\"total_vram\"} * 100",
     "legendFormat": "Used VRAM"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "amd_gpu_fan{type=\"usage\"}"
    }
   ]
  },
  {
   "title": "VRAM Usage (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "amd_gpu_memory_bytes{gpu=\"0\",type=\"used_vram\"} / 1024 / 1024 / 1024",
     "legendFormat": "Used VRAM"
    },
    {
     "expr": "amd_gpu_memory_bytes{gpu=\"0\",type=\"total_vram\"} / 1024 / 1024 / 1024",
     "legendFormat": "Total VRAM"
    }
   ]
  },
  {
   "title": "Total Power Consumed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg_over_time(amd_gpu_power_watts{gpu=\"0\",type=\"socket\"}[$__range]) * $__range_s / 3600) / 1000",
     "legendFormat": "Total Power"
    }
   ]
  }
 ]
}