name: Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: make build
        
      - name: Generate Release Notes
        run: |
          echo "## What's Changed" > release_notes.md
          # For first release, get all commits
          if ! git describe --tags --abbrev=0 2>/dev/null; then
            echo "### 🎉 First Release" >> release_notes.md
            echo "\nInitial features:" >> release_notes.md
            git log --pretty=format:"* %s" >> release_notes.md
          else
            # For subsequent releases
            PREV_TAG=$(git describe --tags --abbrev=0)
            echo "\nChanges since $PREV_TAG:" >> release_notes.md
            git log "$PREV_TAG"..HEAD --pretty=format:"* %s" >> release_notes.md
          fi
          
          # Add installation instructions
          echo "\n\n## Installation" >> release_notes.md
          echo '```bash\ncurl -sSL https://raw.githubusercontent.com/jkoudela/amd-smi-exporter/main/get.sh | sudo bash\n```' >> release_notes.md

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            amd-smi-exporter
            amd-smi-exporter.service
            install_local.sh
            get.sh
          body_path: release_notes.md
          draft: false
          prerelease: false
